---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: '1science/gradle'
    tag: 'latest'

inputs:
- name: cf-show-env

run:
  path: gradlew
  args: ['clean', 'build']
  dir: cf-show-env/
